<form id="configurablecheckout-login" class="configurablecheckout-login" action="">
    <label for="mini-login"><?php echo $this->__('Email:') ?></label><input type="text" name="login[username]"
                                                                            id="mini-login" class="input-text"/>
    <label for="mini-password"><?php echo $this->__('Password:') ?></label><input type="password" name="login[password]"
                                                                                  id="mini-password"
                                                                                  class="input-text"/>
    <div class="actions">
        <div class="errorMessages"></div>
        <button type="button" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
    </div>
        <span class="please-wait" id="login-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Logging in...') ?>" title="<?php echo $this->__('Logging in...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</form>